# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Double a value
#'
#' This will fucking work at least u motherf*cker
#'
#' @param x An integer vector
#' @export
timesTwo <- function(x) {
    .Call(`_IslaNublar_timesTwo`, x)
}

